[spectrum] #---------------------------------------------------------------------
# PLACEHOLDER: This will be replaced with a filter specification
wvl_reference = '633e-9m' # central wavelength
bandwidth = 0.24 # fraction of wvl_reference

[sources] #---------------------------------------------------------------------

[sources.host]
magnitude = -0.353 #Filter magnitude
spectral_profile = "pickles_uk_23.fits" # host star spectral template (default is Pickles G0)

[sources.companion]
delta_magnitude = 20 #delta filter magnitude
separation = 0.4 # arcsec
spectral_profile = "placeholder.fits" # TBD planet spectral template

[sources.exozodi]
delta_magnitude = 21 #delta filter magnitude
spectral_profile = "zodiacal_001.fits"

[ETC]
pp_gain = 10.0 # Post-processing gain
rawDH_contrast_CBE = 9.7e-9 # "Total raw contrast" from the contrast budget CBE column 2025-04-17
rawDH_contrast_spec = 1.0e-8 # "Total raw contrast" from L2-0198 which is the top line in the contrast budget 2025-04-17

[arm_a] #---------------------------------------------------------------------

[arm_a.general] 
f_number_fpm = 49.655877851383266
f_number_sci_cam = 36.70879621305138
f_eff_fpm = '0.46433211378828493m'
f_eff_sci_cam = '0.14657943442905533m'
version = ''
design_wavelength = '635e-9m' # m - Flows from contrast budget dh["wavelen"] 

[arm_a.pupil] 
aper_clear_OD = '2.43m'
aper_clear_ID = '0.0m'

[arm_a.optics]

[arm_a.optics.wcc_focal_plane]
prop_dist = '0.5105869985134304m'

[arm_a.optics.oap1]
aper_clear_OD = '50.8e-3m'
aper_clear_ID = '0.0m'
focal_length = '0.5105869985134304m'
roc = '1.000203185722913m'
conic = -1
off_axis_dist = '0.14463738266077092m'
surf_rms = '6e-9m' 
psd_b = 10 # cylces/m - C. Mendillo's SCOT Leakage Budget in design docs
psd_c = 2.65 # power law exponent - C. Mendillo's SCOT Leakage Budget in design docs
opd_map = 'opds/OAP1_map.fits'
coating_refl = "coatings/AlMgF2_curve.csv"
coating_refl_rms = 0.005
prop_dist = '0.19117699916497802m'

[arm_a.optics.flat1]
aper_clear_OD = '50.8e-3m'
aper_clear_ID = '0.0m'
focal_length = '0.0m'
roc = '0.0m'
conic = 0
off_axis_dist = '0.0m'
surf_rms = '6e-9m' 
psd_b = 10 # cylces/m - C. Mendillo's SCOT Leakage Budget in design docs
psd_c = 2.65 # power law exponent - C. Mendillo's SCOT Leakage Budget in design docs
opd_map = 'opds/FLAT1_map.fits'
coating_refl = "coatings/AlMgF2_curve.csv"
coating_refl_rms = 0.005
prop_dist = '0.5167086395386105m'

[arm_a.optics.pupil_mask]
aper_clear_OD = '14e-3m'
aper_clear_ID = '0.0m'
prop_dist = '0.07873448943460244m'

[arm_a.optics.oap2]
aper_clear_OD = '25.4e-3m'
aper_clear_ID = '0.0m'
focal_length = '0.1022237526492536m'
roc = '0.2m'
conic = -1
off_axis_dist = '0.03m'
surf_rms = '6e-9m' 
psd_b = 10 # cylces/m - C. Mendillo's SCOT Leakage Budget in design docs
psd_c = 2.65 # power law exponent - C. Mendillo's SCOT Leakage Budget in design docs
opd_map = 'opds/OAP2_map.fits'
coating_refl = "coatings/AlMgF2_curve.csv"
coating_refl_rms = 0.005
prop_dist = '0.1022237526492536m'

[arm_a.optics.int_focal_plane1]
prop_dist = '0.07511509008726716m'

[arm_a.optics.oap3]
aper_clear_OD = '25.4e-3m'
aper_clear_ID = '0.0m'
focal_length = '0.07511509008726716m'
roc = '0.142m'
conic = -1
off_axis_dist = '0.0342m'
surf_rms = '6e-9m' 
psd_b = 10 # cylces/m - C. Mendillo's SCOT Leakage Budget in design docs
psd_c = 2.65 # power law exponent - C. Mendillo's SCOT Leakage Budget in design docs
opd_map = 'opds/OAP3_map.fits'
coating_refl = "coatings/AlMgF2_curve.csv"
coating_refl_rms = 0.005
prop_dist = '0.1216640462422038m'

[arm_a.optics.fsm]
aper_clear_OD = '10e-3m'
aper_clear_ID = '0.0m'
focal_length = '0.0m'
roc = '0.0m'
conic = 0
off_axis_dist = '0.0m'
surf_rms = '6e-9m' 
psd_b = 10 # cylces/m - C. Mendillo's SCOT Leakage Budget in design docs
psd_c = 2.65 # power law exponent - C. Mendillo's SCOT Leakage Budget in design docs
opd_map = 'opds/FSM_map.fits'
coating_refl = "coatings/AlMgF2_curve.csv"
coating_refl_rms = 0.005
prop_dist = '0.05459237814349035m'

[arm_a.optics.flat2]
aper_clear_OD = '25.4e-3m'
aper_clear_ID = '0.0m'
focal_length = '0.0m'
roc = '0.0m'
conic = 0
off_axis_dist = '0.0m'
surf_rms = '6e-9m' 
psd_b = 10 # cylces/m - C. Mendillo's SCOT Leakage Budget in design docs
psd_c = 2.65 # power law exponent - C. Mendillo's SCOT Leakage Budget in design docs
opd_map = 'opds/FLAT2_map.fits'
coating_refl = "coatings/AlMgF2_curve.csv"
coating_refl_rms = 0.005
prop_dist = '0.0806974953607496m'

[arm_a.optics.oap4]
aper_clear_OD = '25.4e-3m'
aper_clear_ID = '0.0m'
focal_length = '0.1129076777227092m'
roc = '0.2m'
conic = -1
off_axis_dist = '0.072m'
surf_rms = '6e-9m' 
psd_b = 10 # cylces/m - C. Mendillo's SCOT Leakage Budget in design docs
psd_c = 2.65 # power law exponent - C. Mendillo's SCOT Leakage Budget in design docs
opd_map = 'opds/OAP4_map.fits'
coating_refl = "coatings/AlMgF2_curve.csv"
coating_refl_rms = 0.005
prop_dist = '0.1129076777227092m'

[arm_a.optics.int_focal_plane2]
prop_dist = '0.11290767855594101m'

[arm_a.optics.oap5]
aper_clear_OD = '25.4e-3m'
aper_clear_ID = '0.0m'
focal_length = '0.11290767855594101m'
roc = '0.2m'
conic = -1
off_axis_dist = '0.072m'
surf_rms = '6e-9m' 
psd_b = 10 # cylces/m - C. Mendillo's SCOT Leakage Budget in design docs
psd_c = 2.65 # power law exponent - C. Mendillo's SCOT Leakage Budget in design docs
opd_map = 'opds/OAP5_map.fits'
coating_refl = "coatings/AlMgF2_curve.csv"
coating_refl_rms = 0.005
prop_dist = '0.06714161347730624m'

[arm_a.optics.dm]
aper_clear_OD = '10.2e-3m'
aper_clear_ID = '0.0m'
n_acts = 34
act_spacing = '300e-6m'
act_coupling = 0.15
max_stroke = '1.5e-6m'
n_bits = 16
coating_refl = "coatings/bmc_dm_au.csv"
coating_refl_rms = 0.005
prop_dist = '0.1234055034338526m'

[arm_a.optics.lp1]
aper_clear_OD = '25.4e-3m'
aper_clear_ID = '0.0m'
surf_rms = '6e-9m' 
psd_b = 10 # cylces/m - C. Mendillo's SCOT Leakage Budget in design docs
psd_c = 2.65 # power law exponent - C. Mendillo's SCOT Leakage Budget in design docs
opd_map = 'opds/LP1_map.fits'
pol_throughput = "transmissive_optics/meadowlark_VIS_pol_transmit.csv"
prop_dist = '0.01099859443087553m'

[arm_a.optics.qwp1]
aper_clear_OD = '25.4e-3m'
aper_clear_ID = '0.0m'
surf_rms = '6e-9m' 
psd_b = 10 # cylces/m - C. Mendillo's SCOT Leakage Budget in design docs
psd_c = 2.65 # power law exponent - C. Mendillo's SCOT Leakage Budget in design docs
opd_map = 'opds/QWP1_map.fits'
pol_throughput = 'none'
prop_dist = '0.08499825769977906m'

[arm_a.optics.oap6]
aper_clear_OD = '25.4e-3m'
aper_clear_ID = '0.0m'
focal_length = '0.46433211378828493m'
roc = '0.9m'
conic = -1
off_axis_dist = '0.151m'
surf_rms = '6e-9m' 
psd_b = 10 # cylces/m - C. Mendillo's SCOT Leakage Budget in design docs
psd_c = 2.65 # power law exponent - C. Mendillo's SCOT Leakage Budget in design docs
opd_map = 'opds/OAP6_map.fits'
coating_refl = "coatings/AlMgF2_curve.csv"
coating_refl_rms = 0.005
prop_dist = '0.46433211378828493m'

[arm_a.optics.fpm]
charge = 6
diam_dot = 0.6 # lamD
prop_dist = '0.20621905307034472m'
throughput = "transmissive_optics/vvc_throughput_vs_lamD.fits"

[arm_a.optics.oap7]
aper_clear_OD = '25.4e-3m'
aper_clear_ID = '0.0m'
focal_length = '0.20621905307034472m'
roc = '0.4m'
conic = -1
off_axis_dist = '0.0705m'
surf_rms = '6e-9m' 
psd_b = 10 # cylces/m - C. Mendillo's SCOT Leakage Budget in design docs
psd_c = 2.65 # power law exponent - C. Mendillo's SCOT Leakage Budget in design docs
opd_map = 'opds/OAP7_map.fits'
coating_refl = "coatings/AlMgF2_curve.csv"
coating_refl_rms = 0.005
prop_dist = '0.25380476511281813m'

[arm_a.optics.lyot_stop]
aper_clear_OD = '25.4e-3m'
aper_clear_ID = '3.7e-3m'
pinhole_separation = '5.89e-3m'
pinhole_angle = '45degree'
pinhole_diam = '100e-6m'
lyot_ratio = 0.8909222248976645
prop_dist = '0.07842937112339132m'

[arm_a.optics.oap9]
aper_clear_OD = '25.4e-3m'
aper_clear_ID = '0.0m'
focal_length = '0.1464285714571997m'
roc = '0.28m'
conic = -1
off_axis_dist = '0.06m'
surf_rms = '6e-9m' 
psd_b = 10 # cylces/m - C. Mendillo's SCOT Leakage Budget in design docs
psd_c = 2.65 # power law exponent - C. Mendillo's SCOT Leakage Budget in design docs
opd_map = 'opds/OAP9_map.fits'
coating_refl = "coatings/AlMgF2_curve.csv"
coating_refl_rms = 0.005
prop_dist = '0.1464285714571997m'

[arm_a.optics.field_stop]
prop_dist = '0.140786700680841m'

[arm_a.optics.sphere]
aper_clear_OD = '25.4e-3m'
aper_clear_ID = '0.0m'
focal_length = '0.140786700680841m'
roc = '0.28m'
conic = 0
off_axis_dist = '0.021m'
surf_rms = '6e-9m' 
psd_b = 10 # cylces/m - C. Mendillo's SCOT Leakage Budget in design docs
psd_c = 2.65 # power law exponent - C. Mendillo's SCOT Leakage Budget in design docs
opd_map = 'opds/SPHERE_map.fits'
coating_refl = "coatings/AlMgF2_curve.csv"
coating_refl_rms = 0.005
prop_dist = '0.3192111065688332m'

[arm_a.optics.filter]
aper_clear_OD = '25.4e-3m'
aper_clear_ID = '0.0m'
surf_rms = '6e-9m' 
psd_b = 10 # cylces/m - C. Mendillo's SCOT Leakage Budget in design docs
psd_c = 2.65 # power law exponent - C. Mendillo's SCOT Leakage Budget in design docs
opd_map = 'opds/FILTER_map.fits'
prop_dist = '0.15540687479124612m'
lam_central = '633.0nm' #central wavelength of filter THIS IS TEMPORARY UNTIL AN ACTUAL FILTER CURVE IS AVAILABLE
bandwidth = 0.02 # fraction of central wavelength bandwidth THIS IS TEMPORARY UNTIL AN ACTUAL FILTER CURVE IS AVAILABLE

[arm_a.optics.qwp2]
aper_clear_OD = '25.4e-3m'
aper_clear_ID = '0.0m'
surf_rms = '6e-9m' 
psd_b = 10 # cylces/m - C. Mendillo's SCOT Leakage Budget in design docs
psd_c = 2.65 # power law exponent - C. Mendillo's SCOT Leakage Budget in design docs
opd_map = 'opds/QWP2_map.fits'
pol_throughput = 'none'
prop_dist = '0.01061985976562573m'

[arm_a.optics.lp2]
aper_clear_OD = '25.4e-3m'
aper_clear_ID = '0.0m'
surf_rms = '6e-9m' 
psd_b = 10 # cylces/m - C. Mendillo's SCOT Leakage Budget in design docs
psd_c = 2.65 # power law exponent - C. Mendillo's SCOT Leakage Budget in design docs
opd_map = 'opds/LP2_map.fits'
pol_throughput = "transmissive_optics/meadowlark_VIS_pol_transmit.csv"
prop_dist = '0.08357002309866585m'

[arm_a.optics.oap10]
aper_clear_OD = '25.4e-3m'
aper_clear_ID = '0.0m'
focal_length = '0.14657943442905533m'
roc = '0.28m'
conic = -1
off_axis_dist = '0.06m'
surf_rms = '6e-9m' 
psd_b = 10 # cylces/m - C. Mendillo's SCOT Leakage Budget in design docs
psd_c = 2.65 # power law exponent - C. Mendillo's SCOT Leakage Budget in design docs
opd_map = 'opds/OAP10_map.fits'
coating_refl = "coatings/AlMgF2_curve.csv"
coating_refl_rms = 0.005
prop_dist = '0.14657943442905533m'

[arm_a.sensor]
exposure_time = 1                   # seconds
black_level = 100
gain = 100
pixel_size = '3.76e-6m'                # meters
qe = "sensors/ZWO_ASI6200MM_Pro_QE_curve.csv" 
dark_current = "sensors/ZWO_ASI6200MM_Pro_Dark_Current_vs_Sensor_Temperature.csv"
gain_curve = "sensors/ZWO_ASI6200MM_Pro_Gain_vs_Gain_Setting.csv"
read_noise = "sensors/ZWO_ASI6200MM_Pro_Read_Noise_vs_Gain_Setting.csv"
well_depth = "sensors/ZWO_ASI6200MM_Pro_Well_Depth_vs_Gain_Setting.csv"
temp_nominal = 0                    # Celsius
temp_nominal_range = 1              # Kelvin
temp_stability = 0.1                # Kelvin/hr

[llowfs] #---------------------------------------------------------------------

[llowfs.general]
f_eff = '0.2m'
f_number = 48.15795810257646
defocus = '5e-3m'

[llowfs.pupil]
aper_clear_OD = '4.153e-3m'
aper_clear_ID = '3.7e-3m'

[llowfs.optics]

[llowfs.optics.oap8]
aper_clear_OD = '25.4e-3m'
aper_clear_ID = '0.0m'
focal_length = '0.2m' # OR COULD BE 0.11296m NEED TO ASK KIAN 
roc = '0.2m'
conic = -1
off_axis_dist = '0.072m'
surf_rms = '6e-9m' 
psd_b = 10 # cylces/m - C. Mendillo's SCOT Leakage Budget in design docs
psd_c = 2.65 # power law exponent - C. Mendillo's SCOT Leakage Budget in design docs
opd_map = 'opds/OAP8_map.fits'
coating_refl = "coatings/AlMgF2_curve.csv"
coating_refl_rms = 0.005
prop_dist = '0.2m' # OR COULD BE 0.11296m NEED TO ASK KIAN 

[llowfs.sensor]
exposure_time = 1                   # seconds
black_level = 100
gain = 100
pixel_size = 3.76e-6                # meters
qe = "sensors/ZWO_ASI6200MM_Pro_QE_curve.fits" 
dark_current = "sensors/ZWO_ASI6200MM_Pro_Dark_Current_vs_Sensor_Temperature.csv"
gain_curve = "sensors/ZWO_ASI6200MM_Pro_Gain_vs_Gain_Setting.csv"
read_noise = "sensors/ZWO_ASI6200MM_Pro_Read_Noise_vs_Gain_Setting.csv"
well_depth = "sensors/ZWO_ASI6200MM_Pro_Well_Depth_vs_Gain_Setting.csv"
temp_nominal = 0                    # Celsius
temp_nominal_range = 1              # Kelvin
temp_stability = 0.1                # Kelvin/hr






