[postprocessing]
postprocess_factor = 0.1                # ppFact: This is actually a post-processing object parameter.

[zodi]
magnitude = 22.5
spectral_profile = "PLACEHOLDER.fits"

[exozodi]
magnitude = 22

[optics]
pupil_diameter = 4                      # pupilDiam: Primary mirror major diameter (meters)
obscure_factor = 0.1                    # obscurFac: Primary mirror obscuration factor
shape_factor = 0.785398163397           # shapeFac, pi/4: Primary mirror shape factor (In essence, what number should be multiplied by a^2 to get the mirror area, where a^2 is the major diameter of the mirror)
integration_cutoff = 50                 # intCutoff: Integration time cutoff (days)
stability_factor = 1                    # stabilityFact: Stability factor for speckle stability (does this matter? we're in space???)
cache_dir = "~/.EXOSIMS/cache"          # cachedir: Path to the cache directory
use_planet_shot_noise = false           # texp_flag: Toggles use of planet shot noise valuef or frame exposure time
use_core_throughput_for_ez = false      # use_core_throughput_for_ez: Should exozodi contribution be calculated using core_thruput (True) or occ_trans (False)?


[optics.instrument]
name = "esc"                            # name
qe = 0.9                                # QE: Detector Quantum Efficiency
optical_attenuation = 0.5               # optics: Optical attenuation from all optical elements aside from the detector chip QE & attenuation accounted for in your starlight suppression system
fov = 10                                # FoV: Half-field of view of detector (arcsec)
pixel_number = 1000                     # pixelNumber: Num. of pix. across the detector
pixel_size = 1e-5                       # pixelSize: Distance between pixel centers a.k.a. pixel pitch (m)
pixel_scale = 0.02                      # pixelScale: FoV of an individual pixel (arcsec) Note: This is not a half-FOV like above, it's the full FOV of a pixel. So pixelScale * pixelNumber/2 ~ FoV
read_noise = 1e-6                       # sread: (e/pix/read)
dark_current = 1e-4                     # idark: (e/pix/s)
exposure_time = 100                     # texp: Default single exposure time (s)
spectral_resolution = 50                # Rs: Spectrometers only - Spectral resolving power
lenslet_sampling = 2                    # lenslSamp: Spectrometers only - Lenslet sampling - pixels/lenslet rows

[optics.coronagraph]
name = "vvc"                            # name
lambda_center = 500                     # lam: Central wavelength (nm) - E2ES: wvl_reference
bandwidth = 0.1                         # BW: Since delta lam is often quoted for filters, the relationship is lam * BW = delta lam
extended_source_transmission = 0.2      # occ_trans: Coronagraph transmission for an extended source
point_source_transmission = 0.1         # core_thruput: Coronagraph transmission for a point source
contrast = 1e-10                        # core_contrast: Contrast to assume for observations
contrast_floor = nan                    # contrast_floor: Best possible contrast achievable
platescale = nan                        # core_platescale: Core plate scale (in units of core_platescale_units), e.g. arcsec/mm Note: This definition is assumed. Double check if it needs to be an angle/length or angle/pix
platescale_units = nan                  # core_platescale_units: Units used in core_platescale, e.g. arcsec/mm Note: This definition is assumed. Double check if it's angle/length or angle/pix
angle_units = "arcsec"                  # input_angle_units: Units to assume for angular measurements
overhead_time = 1                       # ohTime: Overhead time added to each observation on top of observatory settling time (days)
inner_working_angle = 0.1               # IWA: inner wroking angle in angle_units
outer_working_angle = inf               # OWA: outer working angle in angle_units
sun_keepout = [0, 180]                  # koAngles_Sun: Sun keep-out angles (deg)
earth_keepout = [0, 180]                # koAngles_Earth: Earth keep-out angles (deg)
moon_keepout = [0, 180]                 # koAngles_Moon: Moon keep-out angles (deg)
other_keepout = [0, 180]                # koAngles_Small: Keep-out angles for other bodes (deg) (unclear what "other bodies" means exactly...)
angular_separation_column_name = "r_as" # csv_angsep_colname: Name of the column in csvs for angular separation

[optics.observing_mode]
instrument_name = "esc"                 # instName
coronagraph_name = "vvc"                # systName
detection_mode = true                   # detectionMode: True if this obsering mode is the detction mode, otherwise false. Only one obsering mdoe can be the detection mode
snr_target = 5                          # SNR: Target SNR for any given observation
integration_time_multiplier = 1.0       # timeMultiplier: Every integration time calculated using this observing mode is scaled by this factor. Ex: you need 2 rolls per target. This factor is 2 then.
lambda_center = 500                     # lam: Central wavelength
delta_lambda = 50                       # deltaLam: Bandwidth in units of length
bandwidth = 0.1                         # BW: Bandwidth as a fraction of central wavelength. If both delta_lambda and bandwidth are set, it preferentially uses delta_lambda and recomputes the bandwidth accordingly.
bandpass_model = "box"                  # bandpass_model: Model to use for bandpasses. Either "gaussian" or "box"
bandpass_step = 0.1                     # bandpass_step: Step size to use for generating box-model bandpasses
