title = "Pearl ESC Baseline Configuration"

[simulation] #---------------------------------------------------------------------
beam_sampling = 512                 # pixels
fov = 128                           # pixels
wvl_sampling = 24      

[digging]
[digging.howfs]

[digging.lowfs]

[maintenance]
[maintenance.howfs]

[maintenance.lowfs]




